### ISSUE TITLE
请求将固件作为 GitHub Release 发布

### ISSUE THREAD

**Issue by qwqVictor** [fortitudepub/padavan-newifi3#1]
您好，您的 Padavan-NEWIFI3 固件之前放在百度云盘上。但现在百度云盘链接已经失效，而 GitHub Release 是一个稳定的二进制分发平台。希望您可以把编译的 trx 文件放在 GitHub Release 上发布，谢谢。

**Comment by unixapple** [comment]
近期有需要更新了一下image，增加了curl工具到固件里，已经上传至binary，需要的话可以自行下载后解压刷新固件。
